version: "3"
services:
  database:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: BnBDb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - 9000:80
    depends_on:
      - database
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./backend:/app
    restart: always
    env_file:
      - ./backend/.env
    environment:
      FLASK_ENV: development
      FLASK_APP: bnbgotit.py
      FLASK_DEBUG: 1
    depends_on:
      - database


  # frontend:
  #   container_name: frontend
  #   restart: always
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  database:
